# Generated by Django 2.1.5 on 2019-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('arrive_date', models.DateTimeField(verbose_name='arrive date')),
                ('pas_num', models.IntegerField(default=1)),
                ('share_valid', models.BooleanField(default=False)),
                ('share_max_num', models.IntegerField(default=1)),
                ('share_name', models.CharField(max_length=200)),
                ('share_number', models.IntegerField(default=1)),
                ('driver_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
