# Generated by Django 2.1.5 on 2019-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_requestride'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestride',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='requestride',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
