# Generated by Django 2.1.5 on 2019-02-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20190203_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
                ('start_date_0', models.DateTimeField(verbose_name='start date')),
                ('start_date_1', models.DateTimeField(verbose_name='start date')),
                ('arrive_date_0', models.DateTimeField(verbose_name='arrive date')),
                ('arrive_date_1', models.DateTimeField(verbose_name='arrive date')),
                ('pas_num', models.IntegerField(default=1)),
            ],
        ),
    ]
