# Generated by Django 2.1.5 on 2019-02-03 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0005_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sharer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='arrive_date_0',
            field=models.DateTimeField(verbose_name='Earliest acceptable arrive date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='arrive_date_1',
            field=models.DateTimeField(verbose_name='Latest acceptable arrive date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='start_date_0',
            field=models.DateTimeField(verbose_name='Earliest acceptable start date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='start_date_1',
            field=models.DateTimeField(verbose_name='Latest acceptable start date'),
        ),
    ]
