# Generated by Django 2.1.5 on 2019-02-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_auto_20190203_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrive_date',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Arrive Date'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pas_num',
            field=models.IntegerField(verbose_name='Passenger Number'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='share_max_num',
            field=models.IntegerField(verbose_name='The maximum sharers you can accept'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='share_number',
            field=models.IntegerField(default=0, verbose_name='Sharer Number'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='share_valid',
            field=models.BooleanField(default=False, verbose_name='Do you want to share the ride with others?'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_date',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Ride Status (open, confirmed, complete)'),
        ),
        migrations.AlterField(
            model_name='share',
            name='arrive_date_0',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Earliest acceptable arrive date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='arrive_date_1',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Latest acceptable arrive date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='share',
            name='start_date_0',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Earliest acceptable start date'),
        ),
        migrations.AlterField(
            model_name='share',
            name='start_date_1',
            field=models.DateTimeField(help_text='Format: 2019-01-01 12:00', verbose_name='Latest acceptable start date'),
        ),
    ]
