# Generated by Django 2.1.5 on 2019-02-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20190203_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='License Plate Number'),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_pas_num',
            field=models.IntegerField(default=0, verbose_name='Maxmium Number of Passengers'),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vehicle Type'),
        ),
    ]
