# Generated by Django 2.1.5 on 2019-02-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(default='SUV', max_length=200),
        ),
    ]
