# Generated by Django 2.1.5 on 2019-02-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='License Plate Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_pas_num',
            field=models.IntegerField(default=0, verbose_name='Maxmium Number of Passengers'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(max_length=200, verbose_name='Vehicle Type'),
        ),
    ]
