# Generated by Django 2.1.5 on 2019-02-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190203_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isDriver',
            field=models.BooleanField(default=False, verbose_name='Do you want to register as a driver?'),
        ),
    ]
